name: cargo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make FireDBG-specific changes
        run: |
            sudo apt-get update
            sudo apt-get install -y clang
            sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
            sudo update-alternatives --set c++ /usr/bin/clang++
      - run: cargo test --all-targets
